//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlphaScan.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Permitzones.xml")]
        public string Filename {
            get {
                return ((string)(this["Filename"]));
            }
            set {
                this["Filename"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BlacklistFile {
            get {
                return ((string)(this["BlacklistFile"]));
            }
            set {
                this["BlacklistFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string IgnoreListFile {
            get {
                return ((string)(this["IgnoreListFile"]));
            }
            set {
                this["IgnoreListFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tmr://pts-ticket-1.dyn.wku.edu")]
        public string ReaderURIs {
            get {
                return ((string)(this["ReaderURIs"]));
            }
            set {
                this["ReaderURIs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("tmr://192.168.0.2")]
        public string ReaderURI {
            get {
                return ((string)(this["ReaderURI"]));
            }
            set {
                this["ReaderURI"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"{<?xml version=""1.0"" encoding=""utf-16""?>\r\n<ArrayOfCamConfigSettings xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">\r\n  <CamConfigSettings>\r\n    <Moniker>@device:pnp:\\?\usb#vid_046d&amp;pid_08d7&amp;mi_00#6&amp;14c7dcf8&amp;0&amp;0000#{65e8773d-8f56-11d0-a3b9-00a0c9223196}\{9b365890-165f-11d0-a195-0020afd156e4}</Moniker>\r\n    <VideoResolution>0</VideoResolution>\r\n    <PhotoResolution>0</PhotoResolution>\r\n    <Antennas>\r\n      <boolean>true</boolean>\r\n      <boolean>true</boolean>\r\n      <boolean>false</boolean>\r\n      <boolean>false</boolean>\r\n    </Antennas>\r\n  </CamConfigSettings>\r\n</ArrayOfCamConfigSettings>}")]
        public string CamSettingsList {
            get {
                return ((string)(this["CamSettingsList"]));
            }
            set {
                this["CamSettingsList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NoReaderMode {
            get {
                return ((bool)(this["NoReaderMode"]));
            }
            set {
                this["NoReaderMode"] = value;
            }
        }
    }
}
